config/routes.rb
Rails.application.routes.draw do
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="https://moodle.griffith.ie/user/view.php?id=82619&course=11239/">Michael Hart</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="http://news.railstutorial.org/">News</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
          <ul class ="nav navbar-nav navbar-right">
            <li><%= link_to "Home",    root_path %></li>
            <li><%= link_to "Help",    help_path %></li>
            <li><%= link_to "Log in",  '#' %></li>
          </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <% javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
	</head>
</html>
<body>
	<h1><%= yield(:title) %></h1>
	<p>
		This website is my first one made using the Ruby on Rails framework.</br>
		Not so bad...</br></br>
		
		All the credits for the tutorial to Michael Hart.
	</p>
</body>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
	</head>
</html>
<body>
	<h1><%= yield(:title) %></h1>
	<p>
		Phone: +33688427634</br>
		Mail: yoan.grandjacques@griffith.ie</br>
		Skype: yoangrandjacques</br>
	</p>
</body>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
	</head>
</html>
<body>
	<h1><%= yield(:title) %></h1>
	<p>
		Why do you need help ? IT'S A SAMPLE APP !
	</p>
</body>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
	</head>
</html>
<body>
	<div class="center jumbotron">
		<h1>Welcome to the Sample App</h1>
		
		<h2>
			This is the home page for the
			<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
			sample application.
		</h2>
		
		<%= link_to "Sign up now !", "https://www.youtube.com/watch?v=dQw4w9WgXcQ", class: "btn btn-lg btn-primary" %>
	</div>
	
	<%= link_to image_tag("rails.png", alt: "Rails logo"), 'http://rubyonrails.org' %>
</body>